[package]
name = "keepstats"
version = "0.1.0"
authors = ["Wspsxing <biluohc@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
lto = "thin"

[build-dependencies]
vergen = "3.1.0"

[dependencies.sqlx]
version = "0.4.0-beta.1"
default-features = false
features = [ "runtime-actix", "macros", "chrono", "decimal", "uuid", "json", "postgres"]
git = "https://github.com/launchbadge/sqlx"
# path = "../sqlx"

[dependencies.web3]
version = "0.14"
default-features = false
features = ["http-tls"] #, "ws-tls-tokio"]
git = "https://github.com/tomusdrw/rust-web3"
# path = "gomain/rust-web3"

[dependencies]
ethabi = "12.0"
ethabi-derive = { version = "12.0", path = "crates/ethabi-derive" }
structopt = "0.3.16"
reqwest = { version = "0.10.5", default-features = false, features = ["rustls-tls", "cookies", "stream", "gzip", "json"] }
tokio = { version = "0.2.22", default-features = false, features = ["rt-core", "rt-util", "io-driver", "tcp", "uds", "udp", "time", "signal", "stream"] }
nonblock-logger = { version = "0.1.5", default-features = false, features = ["color", "dbg"] }
uuid = { version = "0.8.1", features = ["serde", "v4"] }
chrono =  { version = "0.4.15", features = ["serde"] }
rust_decimal = { version = "1.6.0", features = [ "serde-float" ] }
maxminddb = { version = "0.14.0", features = ["mmap"] }
serde = { version = "1.0.115", features = ["derive"] }
serde_qs = "0.6.1"
serde_json = "1.0.57"
json5 = "0.2.8"
rand = "0.7.3"
ring = "0.16.15"
bcrypt = "0.8.2"
hex = "0.4.2"
jsonwebtoken = "7.2.0"
mobc-redis = "0.5.3"
mobc = "0.5.12"
actix-web = "3.0.0"
actix-files = "0.3.0"
actix-rt = "1.1.1"
lazy_static = "1.4.0"
async-trait = "0.1.38"
futures = "0.3.5"
thiserror = "1.0.20"
anyhow = "1.0.32"
url = "2.1.1"
